// src-tauri/src/database.rs
//
// Local-first database targets (Docker Postgres on this machine).
//
// Postgres-backed stacks no longer hard-require a Supabase cloud project up
// front: when no cloud config exists, the pipeline provisions a containerized
// Postgres locally, applies the Prisma schema against it, and verifies
// reachability + tables. Prisma is the portability layer — the same schema
// applies anywhere later (Supabase cloud, Neon, RDS) by changing only
// DATABASE_URL, and data moves with pg_dump/pg_restore (Supabase is Postgres).

use rusqlite::Connection;
use serde::{Deserialize, Serialize};
use std::path::Path;

/// Docker image for the local database (pinned for reproducibility).
pub const LOCAL_DB_IMAGE: &str = "postgres:16-alpine";
/// Host port (Supabase-local convention; avoids clashing with a local 5432).
pub const LOCAL_DB_PORT: u16 = 54322;
pub const LOCAL_DB_USER: &str = "postgres";
pub const LOCAL_DB_NAME: &str = "postgres";
/// Password when POSTGRES_PASSWORD is unset. Local-dev only; never commit it.
pub const LOCAL_DB_PASSWORD_FALLBACK: &str = "postgres";

/// How long to wait for the container to accept connections.
const HEALTH_TIMEOUT_SECS: u64 = 120;

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct DatabaseTarget {
    pub id: String,
    pub project_id: String,
    pub provider: String,
    pub database_url: String,
    pub container_name: Option<String>,
    pub compose_file: Option<String>,
}

#[derive(Debug, Clone, PartialEq)]
pub enum ProvisionError {
    /// Docker is unavailable (daemon down / CLI missing): the operator can fix
    /// this, so the run should pause, not fail.
    DaemonDown(String),
    /// Anything else: a real failure.
    Failed(String),
}

impl std::fmt::Display for ProvisionError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            ProvisionError::DaemonDown(detail) => write!(f, "docker unavailable: {detail}"),
            ProvisionError::Failed(detail) => write!(f, "{detail}"),
        }
    }
}

// ---------------------------------------------------------------------------
// Pure helpers (unit-tested)
// ---------------------------------------------------------------------------

/// `docker-compose.yml` for the local database. The app's DATABASE_URL points
/// at it; only the URL changes when migrating to hosted Postgres later.
pub fn render_compose_yml(password: &str) -> String {
    // NOTE: a raw string with lines starting at column 0. Rust `\`-continuations
    // strip leading whitespace, which once flattened this whole file and
    // produced a duplicate `volumes:` key that only a live `docker compose up`
    // caught. Keep it raw and column-aligned.
    format!(
        r#"# Generated by SourceForge: local Postgres for this project.
# `docker compose up -d db` starts it; the same Prisma schema migrates
# anywhere later (Supabase cloud, Neon, RDS) by changing DATABASE_URL.
services:
  db:
    image: {image}
    environment:
      POSTGRES_USER: {user}
      POSTGRES_PASSWORD: {password}
      POSTGRES_DB: {name}
    ports:
      - "{port}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U {user}"]
      interval: 5s
      timeout: 3s
      retries: 12
volumes:
  pgdata: {{}}
"#,
        image = LOCAL_DB_IMAGE,
        user = LOCAL_DB_USER,
        password = password,
        name = LOCAL_DB_NAME,
        port = LOCAL_DB_PORT,
    )
}

/// Human-readable local database URL for the given password.
pub fn local_database_url(password: &str) -> String {
    format!(
        "postgresql://{user}:{password}@localhost:{port}/{name}",
        user = LOCAL_DB_USER,
        password = password,
        port = LOCAL_DB_PORT,
        name = LOCAL_DB_NAME,
    )
}

/// Password from the environment, falling back to the local-dev default.
pub fn local_db_password() -> String {
    std::env::var("POSTGRES_PASSWORD")
        .ok()
        .filter(|value| !value.trim().is_empty())
        .unwrap_or_else(|| LOCAL_DB_PASSWORD_FALLBACK.to_string())
}

/// Compose project slug derived from the project directory name.
pub fn compose_slug(project_path: &str) -> String {
    let base = Path::new(project_path)
        .file_name()
        .and_then(|name| name.to_str())
        .unwrap_or("app");
    let mut slug: String = base
        .chars()
        .map(|c| if c.is_ascii_alphanumeric() { c.to_ascii_lowercase() } else { '-' })
        .collect();
    slug = slug.trim_matches('-').to_string();
    if slug.is_empty() {
        slug = "app".to_string();
    }
    slug.truncate(40);
    slug
}

/// True when the command output smells like a dead Docker daemon.
pub fn docker_daemon_down(output: &str) -> bool {
    let lower = output.to_lowercase();
    lower.contains("cannot connect to the docker daemon")
        || lower.contains("error during connect")
        || lower.contains("is the docker daemon running")
        || lower.contains("dockerdesktoplinuxengine")
        || lower.contains("the system cannot find the file specified")
}

/// Prisma model names in a schema file (`model User { ... }`).
pub fn prisma_models(schema: &str) -> Vec<String> {
    let mut models = Vec::new();
    for line in schema.lines() {
        let trimmed = line.trim_start();
        if let Some(rest) = trimmed.strip_prefix("model ") {
            let name: String = rest
                .chars()
                .take_while(|c| c.is_alphanumeric() || *c == '_')
                .collect();
            if !name.is_empty() {
                models.push(name);
            }
        }
    }
    models
}

/// Datasource provider declared in the schema (`postgresql`|`sqlite`|...).
/// Scoped to the `datasource` block: the `generator` block also declares a
/// `provider` (`prisma-client-js`).
pub fn schema_provider(schema: &str) -> String {
    let mut in_datasource = false;
    for line in schema.lines() {
        let trimmed = line.trim();
        if trimmed.starts_with("datasource ") {
            in_datasource = true;
            continue;
        }
        if trimmed.starts_with('}') {
            in_datasource = false;
            continue;
        }
        if in_datasource {
            if let Some(rest) = trimmed.strip_prefix("provider") {
                let value: String = rest
                    .trim_start_matches([' ', '=', '\t'])
                    .trim_matches(['\"', '\''])
                    .chars()
                    .take_while(|c| c.is_alphanumeric() || *c == '-' || *c == '_')
                    .collect();
                if !value.is_empty() {
                    return value;
                }
            }
        }
    }
    "postgresql".to_string()
}

/// SQL that resolves each model to its table (NULL / missing row = missing).
/// `to_regclass` is Postgres-only; SQLite exposes `sqlite_master`.
pub fn schema_check_sql(models: &[String], provider: &str) -> String {
    if provider == "sqlite" {
        models
            .iter()
            .map(|model| {
                format!("SELECT name FROM sqlite_master WHERE type='table' AND name='{model}';")
            })
            .collect::<Vec<_>>()
            .join("\n")
    } else {
        models
            .iter()
            .map(|model| format!("SELECT to_regclass('public.\"{model}\"');"))
            .collect::<Vec<_>>()
            .join("\n")
    }
}

/// Models with no matching table in the query output.
pub fn missing_tables(stdout: &str, models: &[String], provider: &str) -> Vec<String> {
    models
        .iter()
        .filter(|model| {
            if provider == "sqlite" {
                !stdout.lines().any(|line| {
                    let cell = line.trim().trim_matches('"');
                    cell == model.as_str()
                })
            } else {
                !stdout.contains(&format!("public.\"{model}\""))
                    && !stdout.contains(&format!("public.{model}"))
            }
        })
        .map(|model| model.to_string())
        .collect()
}

// ---------------------------------------------------------------------------
// Docker plumbing
// ---------------------------------------------------------------------------

fn docker(args: &[&str]) -> Result<(bool, String), String> {
    let output = std::process::Command::new("docker")
        .args(args)
        .output()
        .map_err(|e| format!("cannot start docker: {e}"))?;
    let mut text = String::from_utf8_lossy(&output.stdout).to_string();
    text.push_str(&String::from_utf8_lossy(&output.stderr));
    Ok((output.status.success(), text.trim().to_string()))
}

fn daemon_up() -> bool {
    docker(&["info"]).map(|(ok, _)| ok).unwrap_or(false)
}

fn container_id(compose_file: &str, slug: &str) -> Result<String, String> {
    let (ok, out) = docker(&[
        "compose",
        "-f",
        compose_file,
        "-p",
        slug,
        "ps",
        "-q",
        "db",
    ])?;
    if !ok {
        return Err(format!("docker compose ps failed: {out}"));
    }
    let id = out.lines().next().unwrap_or_default().trim().to_string();
    if id.is_empty() {
        return Err("no container id reported for the db service".to_string());
    }
    Ok(id)
}

fn wait_healthy(container: &str) -> Result<(), String> {
    let deadline = std::time::Instant::now() + std::time::Duration::from_secs(HEALTH_TIMEOUT_SECS);
    loop {
        match docker(&["exec", container, "pg_isready", "-U", LOCAL_DB_USER]) {
            Ok((true, _)) => return Ok(()),
            _ => {
                if std::time::Instant::now() >= deadline {
                    return Err(format!(
                        "postgres did not become healthy within {HEALTH_TIMEOUT_SECS}s"
                    ));
                }
                std::thread::sleep(std::time::Duration::from_secs(2));
            }
        }
    }
}

// ---------------------------------------------------------------------------
// Target record
// ---------------------------------------------------------------------------

pub fn get_target(conn: &Connection, project_id: &str) -> Result<Option<DatabaseTarget>, String> {
    let mut stmt = conn
        .prepare(
            "SELECT id, project_id, provider, database_url, container_name, compose_file
             FROM database_targets WHERE project_id = ?1",
        )
        .map_err(|e| e.to_string())?;
    let mut rows = stmt
        .query_map(rusqlite::params![project_id], |row| {
            Ok(DatabaseTarget {
                id: row.get(0)?,
                project_id: row.get(1)?,
                provider: row.get(2)?,
                database_url: row.get(3)?,
                container_name: row.get(4)?,
                compose_file: row.get(5)?,
            })
        })
        .map_err(|e| e.to_string())?;
    match rows.next() {
        Some(row) => Ok(Some(row.map_err(|e| e.to_string())?)),
        None => Ok(None),
    }
}

pub fn record_target(
    conn: &Connection,
    project_id: &str,
    provider: &str,
    database_url: &str,
    container_name: Option<&str>,
    compose_file: Option<&str>,
) -> Result<DatabaseTarget, String> {
    let now = chrono::Utc::now().to_rfc3339();
    let id = format!("dbt-{}", uuid::Uuid::new_v4());
    conn.execute(
        "INSERT INTO database_targets
            (id, project_id, provider, database_url, container_name, compose_file, created_at, updated_at)
         VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?7)
         ON CONFLICT(project_id) DO UPDATE SET
            provider = excluded.provider,
            database_url = excluded.database_url,
            container_name = excluded.container_name,
            compose_file = excluded.compose_file,
            updated_at = excluded.updated_at",
        rusqlite::params![id, project_id, provider, database_url, container_name, compose_file, now],
    )
    .map_err(|e| e.to_string())?;
    get_target(conn, project_id)?
        .ok_or_else(|| "database target vanished after recording".to_string())
}

// ---------------------------------------------------------------------------
// Provision + schema + checks
// ---------------------------------------------------------------------------

/// Record a file-backed SQLite target. No daemon, no container, no cloud
/// account: the lightest local database. Prisma resolves `file:./dev.db`
/// relative to the schema file, so the URL stays portable. Returning an
/// existing row keeps resume idempotent.
pub fn ensure_sqlite_target(
    conn: &Connection,
    project_id: &str,
    database_url: &str,
    project_path: &str,
) -> Result<DatabaseTarget, String> {
    if let Some(target) = get_target(conn, project_id)? {
        return Ok(target);
    }
    std::fs::create_dir_all(project_path)
        .map_err(|e| format!("cannot create project dir: {e}"))?;
    record_target(conn, project_id, "sqlite", database_url, None, None)
}

/// Ensure a local Docker Postgres exists for the project, starting the
/// container when needed. Idempotent: an existing healthy target is returned
/// as-is, which is what makes resume safe.
pub fn ensure_local_postgres(
    conn: &Connection,
    project_id: &str,
    project_path: &str,
) -> Result<DatabaseTarget, ProvisionError> {
    if let Some(target) = get_target(conn, project_id).map_err(ProvisionError::Failed)? {
        if target.provider == "local-docker" {
            if let Some(container) = target.container_name.clone() {
                if docker(&["exec", &container, "pg_isready", "-U", LOCAL_DB_USER])
                    .map(|(ok, _)| ok)
                    .unwrap_or(false)
                {
                    return Ok(target);
                }
            }
            // Recorded but not running: fall through and (re)start it.
        } else {
            return Ok(target);
        }
    }

    if !daemon_up() {
        return Err(ProvisionError::DaemonDown(
            "start Docker Desktop (or connect a Supabase cloud project instead)".to_string(),
        ));
    }

    let compose_file = Path::new(project_path).join("docker-compose.yml");
    if !compose_file.exists() {
        std::fs::write(&compose_file, render_compose_yml(&local_db_password()))
            .map_err(|e| ProvisionError::Failed(format!("cannot write docker-compose.yml: {e}")))?;
    }
    let compose = compose_file.to_string_lossy().to_string();
    let slug = compose_slug(project_path);

    let (ok, out) = docker(&["compose", "-f", &compose, "-p", &slug, "up", "-d", "db"])
        .map_err(ProvisionError::Failed)?;
    if !ok {
        if docker_daemon_down(&out) {
            return Err(ProvisionError::DaemonDown(out));
        }
        return Err(ProvisionError::Failed(format!("docker compose up failed: {out}")));
    }

    let container = container_id(&compose, &slug).map_err(ProvisionError::Failed)?;
    wait_healthy(&container).map_err(ProvisionError::Failed)?;

    let url = local_database_url(&local_db_password());
    record_target(
        conn,
        project_id,
        "local-docker",
        &url,
        Some(&container),
        Some(&compose),
    )
    .map_err(ProvisionError::Failed)
}

/// Apply the Prisma schema against the project's DATABASE_URL.
///
/// `migrate deploy` when a migrations directory exists, otherwise `db push`
/// (greenfield/POC). Fails the run — a schema that cannot be applied must not
/// be "verified" later.
pub fn apply_prisma_schema(project_path: &str) -> Result<String, String> {
    let base = Path::new(project_path);
    if !base.join("prisma").join("schema.prisma").exists() {
        return Ok("no prisma schema — nothing to apply".to_string());
    }
    let has_migrations = base.join("prisma").join("migrations").is_dir();
    let args: Vec<&str> = if has_migrations {
        vec!["prisma", "migrate", "deploy"]
    } else {
        vec!["prisma", "db", "push"]
    };

    crate::verification::npm_command("npx")
        .args(&args)
        .current_dir(base)
        .stdout(std::process::Stdio::null());
    run_prisma(base, &args)
}

fn run_prisma(base: &Path, args: &[&str]) -> Result<String, String> {
    let mut cmd = crate::verification::npm_command("npx");
    cmd.args(args).current_dir(base);
    crate::pipeline::run_with_timeout(cmd, 300)
        .map(|_| format!("prisma {} applied", args.join(" ")))
}

/// Prove the database is reachable and carries the schema's tables, through the
/// project's own Prisma toolchain (same path the app uses).
///
/// Returns `Ok(None)` when the project has no Prisma schema (nothing to check),
/// `Ok(Some(detail))` on success, `Err` on any failure.
pub fn check_database(project_path: &str) -> Result<Option<String>, String> {
    let base = Path::new(project_path);
    let schema = base.join("prisma").join("schema.prisma");
    if !schema.exists() {
        return Ok(None);
    }
    let text = std::fs::read_to_string(&schema).map_err(|e| e.to_string())?;
    let models = prisma_models(&text);
    if models.is_empty() {
        return Err("prisma schema defines no models — nothing can be verified".to_string());
    }
    if !base.join("node_modules").exists() {
        return Err(
            "node_modules not installed — install dependencies before database verification"
                .to_string(),
        );
    }

    let provider = schema_provider(&text);
    if provider == "sqlite" {
        // `db execute` prints no result rows on SQLite ("Script executed
        // successfully."), so probe each table with a COUNT that fails loudly
        // (`no such table`) when the table is absent.
        let mut missing = Vec::new();
        for model in &models {
            let sql = format!("SELECT COUNT(*) FROM \"{model}\";");
            match prisma_execute_stdin(base, &sql) {
                Ok(_) => {}
                Err(error) if error.contains("no such table") => missing.push(model.clone()),
                Err(error) => return Err(format!("database query failed: {error}")),
            }
        }
        return if missing.is_empty() {
            Ok(Some(format!(
                "database reachable; tables present: {}",
                models.join(", ")
            )))
        } else {
            Err(format!("tables missing in the database: {}", missing.join(", ")))
        };
    }

    let sql = schema_check_sql(&models, &provider);
    let stdout = prisma_execute_stdin(base, &sql)?;
    let missing = missing_tables(&stdout, &models, &provider);
    if missing.is_empty() {
        Ok(Some(format!(
            "database reachable; tables present: {}",
            models.join(", ")
        )))
    } else {
        Err(format!("tables missing in the database: {}", missing.join(", ")))
    }
}

/// Run one SQL script through the project's Prisma (`db execute --stdin`),
/// returning stdout. Used for both Postgres (result rows) and SQLite probes.
fn prisma_execute_stdin(base: &Path, sql: &str) -> Result<String, String> {
    let mut child = crate::verification::npm_command("npx")
        .args(["prisma", "db", "execute", "--stdin", "--schema", "prisma/schema.prisma"])
        .current_dir(base)
        .stdin(std::process::Stdio::piped())
        .stdout(std::process::Stdio::piped())
        .stderr(std::process::Stdio::piped())
        .spawn()
        .map_err(|e| format!("cannot start prisma db execute: {e}"))?;

    {
        use std::io::Write;
        if let Some(stdin) = child.stdin.take() {
            let mut stdin = stdin;
            let _ = stdin.write_all(sql.as_bytes());
        }
    }
    let output = child
        .wait_with_output()
        .map_err(|e| format!("prisma db execute failed: {e}"))?;
    if !output.status.success() {
        let tail = format!(
            "{}{}",
            String::from_utf8_lossy(&output.stdout),
            String::from_utf8_lossy(&output.stderr)
        );
        let lines: Vec<&str> = tail.lines().rev().take(4).collect();
        return Err(lines.into_iter().rev().collect::<Vec<_>>().join(" | "));
    }
    Ok(String::from_utf8_lossy(&output.stdout).to_string())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_compose_yml_pins_image_port_and_healthcheck() {
        let yml = render_compose_yml("secret");
        assert!(yml.contains("postgres:16-alpine"), "pinned image:\n{yml}");
        assert!(yml.contains("54322:5432"), "host port:\n{yml}");
        assert!(yml.contains("pg_isready"), "healthcheck:\n{yml}");
        assert!(yml.contains("pgdata:/var/lib/postgresql/data"), "volume:\n{yml}");
        assert!(yml.contains("POSTGRES_PASSWORD: secret"));
        assert!(!yml.contains("supabase.co"), "no cloud URLs in the local file");
        // Structural: indentation must survive rendering. A flattened file has
        // every key at column 0 and compose rejects the duplicate `volumes:`.
        assert!(yml.contains("\n  db:\n"), "nested service:\n{yml}");
        assert!(yml.contains("\n    image: postgres:16-alpine\n"), "nested image:\n{yml}");
        assert!(yml.contains("\nvolumes:\n"), "top-level volumes:\n{yml}");
        assert!(!yml.contains("\ndb:\n"), "service must be nested:\n{yml}");
        assert!(!yml.contains("\nimage: "), "keys must be nested:\n{yml}");
    }

    #[test]
    fn test_compose_slug_is_safe() {
        assert_eq!(compose_slug("/tmp/My App_2"), "my-app-2");
        assert_eq!(compose_slug("/"), "app");
        assert_eq!(compose_slug(""), "app");
    }

    #[test]
    fn test_docker_daemon_down_detection() {
        assert!(docker_daemon_down(
            "error during connect: open //./pipe/dockerDesktopLinuxEngine"
        ));
        assert!(docker_daemon_down("Cannot connect to the Docker daemon"));
        assert!(!docker_daemon_down("CONTAINER ID   IMAGE"));
    }

    #[test]
    fn test_prisma_models_parses_schema() {
        let schema = "generator client {\n  provider = \"x\"\n}\n\nmodel User {\n  id String @id\n}\n\n// model Commented {\nmodel Post {\n  id String @id\n}\n";
        assert_eq!(prisma_models(schema), vec!["User", "Post"]);
        assert!(prisma_models("no models here").is_empty());
    }

    #[test]
    fn test_schema_check_sql_resolves_tables() {
        let sql = schema_check_sql(&["User".to_string(), "Post".to_string()], "postgresql");
        assert!(sql.contains("to_regclass('public.\"User\"')"));
        assert!(sql.contains("to_regclass('public.\"Post\"')"));

        let sqlite =
            schema_check_sql(&["User".to_string()], "sqlite");
        assert!(sqlite.contains("sqlite_master"));
        assert!(sqlite.contains("name='User'"));
        assert!(!sqlite.contains("to_regclass"), "postgres-only function");
    }

    #[test]
    fn test_schema_provider_reads_the_datasource_block() {
        let schema = "generator client {\n  provider = \"prisma-client-js\"\n}\n\ndatasource db {\n  provider = \"sqlite\"\n  url = \"file:./dev.db\"\n}\n";
        assert_eq!(schema_provider(schema), "sqlite");
        let pg = schema.replace("\"sqlite\"", "\"postgresql\"");
        assert_eq!(schema_provider(&pg), "postgresql");
        assert_eq!(schema_provider("no blocks here"), "postgresql");
    }

    #[test]
    fn test_missing_tables_matches_per_provider() {
        let models = vec!["User".to_string()];
        assert!(missing_tables("public.\"User\"\n", &models, "postgresql").is_empty());
        assert_eq!(missing_tables("", &models, "postgresql"), vec!["User".to_string()]);
        assert!(missing_tables("User\n", &models, "sqlite").is_empty());
        assert_eq!(missing_tables("", &models, "sqlite"), vec!["User".to_string()]);
        // A substring elsewhere must not count for sqlite.
        assert_eq!(
            missing_tables("SuperUser\n", &models, "sqlite"),
            vec!["User".to_string()]
        );
    }

    #[test]
    fn test_ensure_sqlite_target_is_daemon_free_and_idempotent() {
        let conn = Connection::open_in_memory().unwrap();
        conn.execute_batch(
            "CREATE TABLE projects (id TEXT PRIMARY KEY, path TEXT, name TEXT, created_at TEXT, updated_at TEXT);
             INSERT INTO projects (id, path, name, created_at, updated_at)
             VALUES ('proj-s', '/tmp/proj-s', 'PS', datetime('now'), datetime('now'));",
        )
        .unwrap();
        conn.execute_batch(include_str!("../migrations/018_database_targets.sql"))
            .unwrap();
        let dir = tempfile::TempDir::new().unwrap();
        let project = dir.path().join("sub").to_string_lossy().to_string();

        let first =
            ensure_sqlite_target(&conn, "proj-s", "file:./dev.db", &project).unwrap();
        assert_eq!(first.provider, "sqlite");
        assert!(first.container_name.is_none(), "no container for sqlite");
        assert!(Path::new(&project).exists(), "project dir created");

        // Second call returns the recorded row instead of duplicating.
        let second =
            ensure_sqlite_target(&conn, "proj-s", "file:./dev.db", &project).unwrap();
        assert_eq!(first.id, second.id);
    }

    #[test]
    fn test_record_and_get_target_roundtrip() {
        let conn = Connection::open_in_memory().unwrap();
        // Minimal parent for the project_id foreign key.
        conn.execute_batch(
            "CREATE TABLE projects (id TEXT PRIMARY KEY, path TEXT, name TEXT, created_at TEXT, updated_at TEXT);
             INSERT INTO projects (id, path, name, created_at, updated_at)
             VALUES ('proj-1', '/tmp/proj-1', 'P1', datetime('now'), datetime('now'));",
        )
        .unwrap();
        conn.execute_batch(include_str!("../migrations/018_database_targets.sql"))
            .unwrap();
        assert!(get_target(&conn, "proj-1").unwrap().is_none());
        let target = record_target(
            &conn,
            "proj-1",
            "local-docker",
            "postgresql://postgres:postgres@localhost:54322/postgres",
            Some("proj-1-db-1"),
            Some("/tmp/docker-compose.yml"),
        )
        .unwrap();
        assert_eq!(target.provider, "local-docker");
        assert_eq!(target.container_name.as_deref(), Some("proj-1-db-1"));
        // Re-recording is an upsert, not a duplicate.
        record_target(&conn, "proj-1", "local-docker", "postgresql://x", None, None).unwrap();
        let count: i64 = conn
            .query_row(
                "SELECT COUNT(*) FROM database_targets WHERE project_id = 'proj-1'",
                [],
                |row| row.get(0),
            )
            .unwrap();
        assert_eq!(count, 1);
    }

    /// Live test: boots a real container when Docker is available, and passes
    /// vacuously (with a note) when it is not — so CI without Docker stays green.
    #[test]
    #[ignore = "needs a running Docker engine; run explicitly with --ignored"]
    fn test_live_local_postgres_roundtrip() {
        if !daemon_up() {
            println!("docker daemon is down — skipping live container test");
            return;
        }
        let dir = tempfile::TempDir::new().unwrap();
        let project = dir.path().to_string_lossy().to_string();
        let conn = Connection::open_in_memory().unwrap();
        conn.execute_batch(
            "CREATE TABLE projects (id TEXT PRIMARY KEY, path TEXT, name TEXT, created_at TEXT, updated_at TEXT);
             INSERT INTO projects (id, path, name, created_at, updated_at)
             VALUES ('proj-live', '/tmp/proj-live', 'PL', datetime('now'), datetime('now'));",
        )
        .unwrap();
        conn.execute_batch(include_str!("../migrations/018_database_targets.sql"))
            .unwrap();

        let target =
            ensure_local_postgres(&conn, "proj-live", &project).expect("provision container");
        assert_eq!(target.provider, "local-docker");
        assert!(target.database_url.contains("localhost:54322"));

        let (ok, out) = docker(&[
            "exec",
            target.container_name.as_deref().unwrap(),
            "psql",
            "-U",
            "postgres",
            "-d",
            "postgres",
            "-tAc",
            "SELECT 1",
        ])
        .unwrap();
        assert!(ok && out.trim() == "1", "psql roundtrip: {out}");

        // Cleanup: stop the container and drop the worktree files.
        let compose = dir.path().join("docker-compose.yml").to_string_lossy().to_string();
        let slug = compose_slug(&project);
        let _ = docker(&["compose", "-f", &compose, "-p", &slug, "down", "-v"]);
    }
}
