// src-tauri/src/deployer.rs
//
// Deployment seam for the build pipeline (SPEC-001 §5 DG-1 / §6 decision 1).
// v1: Vercel CLI execution + generic Dockerfile artifact generation.

use std::path::{Path, PathBuf};
use std::process::Command;

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct DeployOutcome {
    pub provider: String,
    pub url: Option<String>,
    pub detail: String,
}

pub trait Deployer: Send + Sync {
    fn deploy(&self, project_path: &Path, stack_id: &str) -> Result<DeployOutcome, String>;
}

/// Runs `vercel deploy --prod --yes` in the project directory.
pub struct VercelDeployer;

impl Deployer for VercelDeployer {
    fn deploy(&self, project_path: &Path, stack_id: &str) -> Result<DeployOutcome, String> {
        let output = Command::new("vercel")
            .args(["deploy", "--prod", "--yes"])
            .current_dir(project_path)
            .output()
            .map_err(|e| format!("Cannot run vercel CLI: {e}"))?;

        let stdout = String::from_utf8_lossy(&output.stdout).to_string();
        let stderr = String::from_utf8_lossy(&output.stderr).to_string();

        if !output.status.success() {
            let detail = if stderr.trim().is_empty() {
                stdout.trim().to_string()
            } else {
                stderr.trim().to_string()
            };
            return Err(format!("vercel deploy failed: {detail}"));
        }

        let url = stdout.lines().rev().find_map(|line| {
            let trimmed = line.trim().trim_end_matches('.');
            if trimmed.starts_with("https://") {
                Some(trimmed.to_string())
            } else {
                None
            }
        });

        Ok(DeployOutcome {
            provider: "vercel".to_string(),
            url,
            detail: format!("stack={stack_id}"),
        })
    }
}

/// Test double: never touches the network.
pub struct MockDeployer {
    pub url: String,
    pub fail: bool,
}

impl Deployer for MockDeployer {
    fn deploy(&self, _project_path: &Path, stack_id: &str) -> Result<DeployOutcome, String> {
        if self.fail {
            return Err("mock deploy failure".to_string());
        }
        Ok(DeployOutcome {
            provider: "mock".to_string(),
            url: Some(self.url.clone()),
            detail: format!("stack={stack_id}"),
        })
    }
}

/// Write a generic Dockerfile artifact for non-Vercel hosts (decision §6.1).
/// Idempotent: returns `None` when a Dockerfile already exists.
pub fn write_dockerfile(project_path: &Path, stack_id: &str) -> Result<Option<PathBuf>, String> {
    let path = project_path.join("Dockerfile");
    if path.exists() {
        return Ok(None);
    }

    let content = format!(
        "# Generated by SourceForge (stack: {stack_id}).\n\
         # Artifact for non-Vercel hosts; not executed by the v1 pipeline.\n\
         FROM node:22-alpine AS build\n\
         WORKDIR /app\n\
         COPY package*.json ./\n\
         RUN npm ci\n\
         COPY . .\n\
         RUN npm run build\n\
         \n\
         FROM node:22-alpine\n\
         WORKDIR /app\n\
         ENV NODE_ENV=production\n\
         COPY --from=build /app ./\n\
         EXPOSE 3000\n\
         CMD [\"npm\", \"start\"]\n"
    );

    std::fs::write(&path, content).map_err(|e| format!("Cannot write Dockerfile: {e}"))?;
    Ok(Some(path))
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    #[test]
    fn test_mock_deployer_returns_url() {
        let dir = TempDir::new().unwrap();
        let outcome = MockDeployer {
            url: "https://mock.example.app".to_string(),
            fail: false,
        }
        .deploy(dir.path(), "nextjs-prisma-vercel")
        .unwrap();

        assert_eq!(outcome.provider, "mock");
        assert_eq!(outcome.url.as_deref(), Some("https://mock.example.app"));
    }

    #[test]
    fn test_mock_deployer_can_fail() {
        let dir = TempDir::new().unwrap();
        let result = MockDeployer {
            url: String::new(),
            fail: true,
        }
        .deploy(dir.path(), "stack");
        assert!(result.is_err());
    }

    #[test]
    fn test_write_dockerfile_creates_then_skips() {
        let dir = TempDir::new().unwrap();

        let created = write_dockerfile(dir.path(), "nextjs-supabase-vercel").unwrap();
        assert!(created.is_some());
        let content = std::fs::read_to_string(dir.path().join("Dockerfile")).unwrap();
        assert!(content.contains("npm ci"));
        assert!(content.contains("nextjs-supabase-vercel"));

        // Idempotent — second call leaves the existing file alone.
        let again = write_dockerfile(dir.path(), "nextjs-supabase-vercel").unwrap();
        assert!(again.is_none());
    }
}
